gmake[1]: Entering directory '/home/juergen/1_dev/projects/Sketchable-Interaction/SI/src/sirose/msg/ros2_si_interface/build/ros2_si_interface'
-- Found ament_cmake: 1.1.5 (/home/juergen/ros2_galactic/install/ament_cmake/share/ament_cmake/cmake)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.9.2", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Found rosidl_default_generators: 1.1.1 (/home/juergen/ros2_galactic/install/rosidl_default_generators/share/rosidl_default_generators/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_introspection_c;rosidl_typesupport_fastrtps_c
-- Found rosidl_adapter: 2.2.1 (/home/juergen/ros2_galactic/install/rosidl_adapter/share/rosidl_adapter/cmake)
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_introspection_cpp;rosidl_typesupport_fastrtps_cpp
-- Found PythonInterp: /usr/bin/python3 (found version "3.9.2") 
CMake Error at /home/juergen/ros2_galactic/install/rosidl_adapter/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
  ros2_si_interface --arguments-file
  /home/juergen/1_dev/projects/Sketchable-Interaction/SI/src/sirose/msg/ros2_si_interface/build/ros2_si_interface/rosidl_adapter__arguments__ros2_si_interface.json
  --output-dir
  /home/juergen/1_dev/projects/Sketchable-Interaction/SI/src/sirose/msg/ros2_si_interface/build/ros2_si_interface/rosidl_adapter/ros2_si_interface
  --output-file
  /home/juergen/1_dev/projects/Sketchable-Interaction/SI/src/sirose/msg/ros2_si_interface/build/ros2_si_interface/rosidl_adapter/ros2_si_interface.idls)
  returned error code 1:

  Error processing 'float32[][] geometry' of 'ros2_si_interface/VTKSIObject':
  ''float32[]' is an invalid message name.  It should have the pattern
  '^[A-Z][A-Za-z0-9]*$''

  Traceback (most recent call last):

    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/juergen/ros2_galactic/install/rosidl_adapter/lib/python3.9/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/home/juergen/ros2_galactic/install/rosidl_adapter/lib/python3.9/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/home/juergen/ros2_galactic/install/rosidl_adapter/lib/python3.9/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/home/juergen/ros2_galactic/install/rosidl_adapter/lib/python3.9/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/home/juergen/ros2_galactic/install/rosidl_adapter/lib/python3.9/site-packages/rosidl_adapter/parser.py", line 516, in parse_message_string
      Type(type_string, context_package_name=pkg_name),
    File "/home/juergen/ros2_galactic/install/rosidl_adapter/lib/python3.9/site-packages/rosidl_adapter/parser.py", line 276, in __init__
      super(Type, self).__init__(
    File "/home/juergen/ros2_galactic/install/rosidl_adapter/lib/python3.9/site-packages/rosidl_adapter/parser.py", line 204, in __init__
      raise InvalidResourceName(

  rosidl_adapter.parser.InvalidResourceName: 'float32[]' is an invalid
  message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'

Call Stack (most recent call first):
  /home/juergen/ros2_galactic/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:13 (rosidl_generate_interfaces)


-- Configuring incomplete, errors occurred!
See also "/home/juergen/1_dev/projects/Sketchable-Interaction/SI/src/sirose/msg/ros2_si_interface/build/ros2_si_interface/CMakeFiles/CMakeOutput.log".
gmake[1]: Leaving directory '/home/juergen/1_dev/projects/Sketchable-Interaction/SI/src/sirose/msg/ros2_si_interface/build/ros2_si_interface'
gmake[1]: *** [Makefile:748: cmake_check_build_system] Error 1
